server:
  port: 8083
  application:
    name: interacao-api
spring:
  datasource:
    url: jdbc:postgresql://postgres-interacao:5432/postgres
    username: admin
    password: senha123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server-1:8761/eureka
